[workspace]
resolver = "2"
members = [
    "crates/wire",
    "crates/identity",
    "crates/translator",
    "crates/control-proto",
    "crates/email-proto",
    "crates/agent",
    "crates/p2claw-iroh-client",
    "crates/p2claw-mobile",
    "libs/identity-verify/rust",
]

[workspace.package]
edition = "2021"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
