//! Drive every committed `libs/identity-verify/test-vectors.json`
//! case through `verify_token`. The fixture is regenerated by
//! `crates/agent`'s `gen-identity-vectors` binary (which mints
//! signature-bearing cases via the daemon's real `attestation::mint`
//! path) and is the cross-language contract every language binding
//! pins against.
//!
//! Schema:
//! ```text
//! {
//!   "trusted_peer_id": "<52-char z-base-32>",
//!   "leeway_secs": 15,
//!   "cases": [
//!     {"name": "positive_oauth_identity", "token": "...", "verify_at": N,
//!      "expect": "ok", "expected_claims": {iss, sub, iat, exp, email, name, auth_method}},
//!     {"name": "negative_<...>", "token": "...", "verify_at": N,
//!      "expect": "err:<VerifyErrorVariant>"}
//!   ]
//! }
//! ```
//! The `err:<Variant>` PascalCase tag is the canonical contract;
//! TS/Python/Go bindings map their own enum variants onto these
//! strings.

use p2claw_identity_verify::{verify_token, VerifyError};
use serde::Deserialize;
use std::path::PathBuf;
use std::time::{Duration, SystemTime};

#[derive(Debug, Deserialize)]
struct Vectors {
    trusted_peer_id: String,
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    token: String,
    verify_at: u64,
    expect: String,
    #[serde(default)]
    expected_claims: Option<ExpectedClaims>,
}

#[derive(Debug, Deserialize)]
struct ExpectedClaims {
    iss: String,
    sub: String,
    iat: u64,
    exp: u64,
    email: Option<String>,
    name: Option<String>,
    auth_method: Option<String>,
}

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("rust/ parent")
        .join("test-vectors.json")
}

fn load_vectors() -> Vectors {
    let raw = std::fs::read_to_string(vectors_path()).expect("read test-vectors.json");
    serde_json::from_str(&raw).expect("parse test-vectors.json")
}

/// `VerifyError` → canonical PascalCase tag matching `expect:"err:<Tag>"`.
fn error_tag(e: &VerifyError) -> &'static str {
    match e {
        VerifyError::TokenMissing => "TokenMissing",
        VerifyError::Malformed(_) => "Malformed",
        VerifyError::BadSignature => "BadSignature",
        VerifyError::Expired => "Expired",
        VerifyError::NotYetValid => "NotYetValid",
        VerifyError::IssuerMismatch { .. } => "IssuerMismatch",
        VerifyError::AlgorithmRejected => "AlgorithmRejected",
        VerifyError::BadPeerId(_) => "BadPeerId",
        _ => "Unknown",
    }
}

#[test]
fn every_committed_vector_matches_expected_outcome() {
    let vectors = load_vectors();
    let mut failures = Vec::new();

    for case in &vectors.cases {
        let now = SystemTime::UNIX_EPOCH + Duration::from_secs(case.verify_at);
        let result = verify_token(&case.token, &vectors.trusted_peer_id, now);

        match (case.expect.as_str(), &result) {
            ("ok", Ok(claims)) => {
                if let Some(want) = &case.expected_claims {
                    if claims.iss != want.iss
                        || claims.sub != want.sub
                        || claims.iat != want.iat
                        || claims.exp != want.exp
                        || claims.email != want.email
                        || claims.name != want.name
                        || claims.auth_method != want.auth_method
                    {
                        failures.push(format!("{}: claims mismatch (got {:?})", case.name, claims));
                    }
                }
            }
            ("ok", Err(e)) => {
                failures.push(format!("{}: expected ok, got Err({:?})", case.name, e));
            }
            (exp_str, _) if !exp_str.starts_with("err:") && exp_str != "ok" => {
                failures.push(format!(
                    "{}: invalid `expect` field: {}",
                    case.name, exp_str
                ));
            }
            (exp_str, Ok(claims)) => {
                failures.push(format!(
                    "{}: expected {}, got Ok({:?})",
                    case.name, exp_str, claims
                ));
            }
            (exp_str, Err(e)) => {
                let want = &exp_str[4..]; // strip "err:" prefix
                let got = error_tag(e);
                if got != want {
                    failures.push(format!(
                        "{}: expected err:{}, got err:{} ({})",
                        case.name, want, got, e
                    ));
                }
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "test-vector mismatches ({} of {}):\n  {}",
            failures.len(),
            vectors.cases.len(),
            failures.join("\n  ")
        );
    }
}
